# Generated by Django 4.0.3 on 2022-04-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.TextField(verbose_name='Haydovchi F.I.O?')),
                ('carnumber', models.CharField(choices=[('90018WAA', '90018WAA'), ('90Y054NA', '90Y054NA'), ('90E077HA', '90E077HA'), ('90H084PA', '90H084PA'), ('90087FBA', '90087FBA'), ('90S087KA', '90S087KA'), ('90G350LA', '90G350LA'), ('90100BAA', '90100BAA'), ('90102WAA', '90102WAA'), ('90200BAA', '90200BAA'), ('90206WAA', '90206WAA'), ('90255WAA', '90255WAA'), ('90279FBA', '90279FBA'), ('90280FBA', '90280FBA'), ('90281FBA', '90281FBA'), ('90283FBA', '90283FBA'), ('90C285OA', '90C285OA'), ('90C285OA', '90C285OA'), ('90M287OA', '90M287OA'), ('90A297LA', '90A297LA'), ('90315WAA', '90315WAA'), ('90316WAA', '90316WAA'), ('01Q370PA', '01Q370PA'), ('90468WAA', '90468WAA'), ('90469WAA', '90469WAA'), ('90M469MA', '90M469MA'), ('90481WAA', '90481WAA'), ('90482WAA', '90482WAA'), ('90M484LA', '90M484LA'), ('90R490BA', '90R490BA'), ('90P064PA', '90P064PA'), ('90615WAA', '90615WAA'), ('90A641LA', '90A641LA'), ('90J651OA', '90J651OA'), ('90Z669EA', '90Z669EA'), ('90J689OA', '90J689OA'), ('90K716NA', '90K716NA'), ('90G768EA', '90G768EA'), ('90J770JA', '90J770JA'), ('90795WAA', '90795WAA'), ('90D832LA', '90D832LA'), ('90A832PA', '90A832PA'), ('90833ABA', '90833ABA'), ('90D893NA', '90D893NA'), ('90C962KA', '90C962KA'), ('90R990LA', '90R990LA')], default='90018WAA', max_length=60, verbose_name='Mashina raqami?')),
                ('regdata', models.DateField(verbose_name='Berilgan sanasi?')),
                ('tirnumber', models.TextField(blank=True, verbose_name="TIR raqami? (agar bo'lsa)")),
                ('waybill', models.TextField(blank=True, verbose_name="Yo'l varaqasi raqami? (agar bo'lsa)")),
                ('cmr1', models.TextField(blank=True, verbose_name="CMR raqami? (agar bo'lsa)")),
                ('cmr2', models.TextField(blank=True, verbose_name="CMR raqami(agar CMR bittadan ko'p bo'lsa)?")),
                ('dazvol', models.TextField(blank=True, verbose_name='Dozvol raqami?')),
                ('tc', models.TextField(blank=True, verbose_name="КОМАНДИРОВОЧНОЕ УДОСТОВЕРЕНИЕ? (agar bo'lsa)")),
                ('tircheck', models.BooleanField(verbose_name='TIR Check')),
                ('waybillcheck', models.BooleanField(verbose_name='WayBill Check')),
                ('cmr1check', models.BooleanField(verbose_name='CMR Check')),
                ('cmr2check', models.BooleanField(verbose_name='CMR-2 Check')),
                ('dcheck', models.BooleanField(verbose_name='Dozvol Check')),
                ('tcheck', models.BooleanField(verbose_name='К/У')),
                ('checker', models.BooleanField(verbose_name='Check All')),
            ],
            options={
                'verbose_name': ('',),
                'verbose_name_plural': 'Hujjatlar',
            },
        ),
    ]
